sequenceDiagram
    participant browser
    participant server
    
    browser->>server: https://studies.cs.helsinki.fi/exampleapp/notes
    activate server
    server-->>browser: HTML document
    deactivate server
    
    browser->>server: https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server
    
    browser->>server: https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server
    
    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{content: "", date: "2023-02-01T15:05:44.718Z"}, {content: "", date: "2023-02-01T15:22:35.945Z"},…]
    deactivate server    

    Note right of browser: The browser executes the callback function that renders the notes 

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note
        Note right of browser: The user enters a note and submits the form. 
    Note right of browser: The browser sends the new note to the server address new_note (note: not contents here).
    
    activate server
    server-->>browser: 302 response. The server requests a new HTTP GET request browser, to fetch the notes (location - browser/exampleapp/notes) & reload the browser.
    deactivate server

    browser->>server: https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file is fetched
    deactivate server
    
    browser->>server: https://studies.cs.helsinki.fi/exampleapp/main.js
    activate server
    server-->>browser: the JavaScript file is fetched
    deactivate server
    
    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server
    
    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "dodo", "date": "2023-01-29T14:16:15.720Z" }, ... ]
    deactivate server 